operations:
  view:
    - type: web
      impl: index.html
actions: actions
web: web-src
hooks:
  pre-app-build: hooks/pre-app-build.js
  pre-app-deploy: hooks/pre-app-deploy.js
runtimeManifest:
  packages:
    example:
      license: Apache-2.0
      actions:
        $include: actions/example/actions.config.yaml
    admin-ui-sdk:
      license: Apache-2.0
      actions:
        $include: actions/admin-ui-sdk/actions.config.yaml
